### ISSUE TITLE
(chrome shim) after 4.1, senders are no longer kept in sync with tracks

### ISSUE THREAD

**Issue by ianwremmel** [webrtcHacks/adapter#615]
**Browsers and versions affected**
Chrome
webrtc-adapter >= 4.1.0

**Description**
`MediaStream.removeTrack()` doesn't clean up senders. 

**Steps to reproduce**
Remove a track from a peer connection's local stream

**Expected results**
The following assertions hold

```js
let senders = pc.getSenders().filter((s) => s.track.kind === `audio`);
assert.lengthOf(senders, 1);

pc.getLocalStreams().forEach((stream) => {
  stream.getAudioTracks().forEach((t) => {
    stream.removeTrack(t);
  });
});

senders = pc.getSenders().filter((s) => s.track.kind === `audio`);
assert.lengthOf(senders, 0);
```

**Actual results**
The second assertion above does not hold.

**Comment by fippo** [comment]
That behaviour does not work in Firefox and from the discussions in #559 is not something that is going to be spec-compliant either. You need to explicitly remove a track (which will be available in #611) to remove its sender (and note that in the future the sender won't be removed but its track will be null'ed)

**Comment by jan-ivar** [comment]
@ianwremmel The behavior you're relying on is entirely Chrome specific, and was never in any spec. 

I recommend [preparing for WebRTC 1.0](https://blog.mozilla.org/webrtc/the-evolution-of-webrtc/).

**Comment by ianwremmel** [comment]
Totally understand that it's not specified, but's a breaking change that, to my knowledge, has no alternative for adapter users. Once #611 gets published, this won't be an issue for me anymore. I *think* the pre-4.1 behavior was there to allow pc.addTrack() and pc.getSenders() to behave as specified while still allowing stream.removeTrack to generate the appropriate negotationneeded event and the expected sdp when createOffer was subsequently called. 

I guess I'll just pin to 4.0 until #611 is published.

**Comment by fippo** [comment]
Well, its a unintentional breaking change aka bug.
I had to do the same and its the reason i'm pushing #611 now ;-)

**Comment by ianwremmel** [comment]
Haha, sounds good. Thanks everyone!

**Comment by fippo** [comment]
we're aiming for a new minor release really soon now. But note that Chrome just landed native support behind a flag: https://bugs.chromium.org/p/chromium/issues/detail?id=700916#c24
You might want to give that a try (and ping @henbos there or here if you notice any differences)

**Comment by fippo** [comment]
so one has to replace
```
localStreams[i].removeTrack(tracks[j]);
localStreams[i].addTrack(newTrack);
```
with
```
pc.removeTrack(senders[i]);
localStreams[j].removeTrack(oldTrack);
localStreams[j].addTrack(newTrack);
pc.addTrack(newTrack, localStreams[j]);
```
-- one still needs getLocalStreams() to implement this replaceTrack alternative. Boo!

**Comment by ianwremmel** [comment]
oh, interesting. so, `pc.removeTrack` doesn't imply removing the track from the peer connection's local track? I think it does in Firefox. Or, is this just temporary behavior until pc.removeTrack is available natively in chrome?

**Comment by fippo** [comment]
oh? On https://webrtc.github.io/samples/src/content/peerconnection/pc1/ calling this doesn't change pc1.getLocalStreams():
```
pc1.removeTrack(pc1.getSenders()[0])
pc1.getLocalStreams()[0].getTracks()
```

**Comment by ianwremmel** [comment]
I think so. I'm pretty sure I've got assertions around having the expected number of tracks in the all the right places. I had hoped to have more details this past week, but couldn't get to it; I'm on vacation for the next week but will followup when I'm back in the office.

**Comment by KaptenJansson** [comment]
Any updates?

**Comment by ianwremmel** [comment]
not so far, a bunch of unrelated things have me distracted.

**Comment by ianwremmel** [comment]
Hi all, sorry for the long delay, but I'm finally able to look into this again. I'm still seeing issues that start at v4.1.0, but they do seem a little different from what I was seeing before. 

webrtc-adapter: 5.0.4
chrome: 61.0.3163

I've got a test where I start with `{audio=inactive, video=sendrecv`, transition to `{audio=inactive, video=recvonly`, and return to `{audio=inactive, video=sendrev}`. The first transition works, but the second fails to restart sending. 

It looks like when i call getUserMedia and addTrack for the second transition, addTrack adds a sender to the peer connection, but there's no stream (the stream seems to have been removed by accepting the answer at the first transition), so when createOffer is called at the second transition, there's no offer to send video, even though there's a sender in the peer connection. If I put the stream back into the peer connection before it starts negotiation, the test passes.

This scenario passes (with and without adapter.js) in Firefox. 

I'm continuing to debug, but if this rings a bell for anyone, I'd love to hear about it. Thanks!

**Comment by ianwremmel** [comment]
it looks like the fix may be as simple as changing the removeTrack shim remove the stream from pc_streams in this block of code:

```js
        if (stream.getTracks().length === 1) {
          // if this is the last track of the stream, remove the stream. This
          // takes care of any shimmed _senders.
          pc.removeStream(stream);
        } else {
```

**Comment by ianwremmel** [comment]
I think I've found the root of the problem. [one of the removeStreams overrides](https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L277-L287) doens't necessarily remove the stream from `pc._streams` when it's stupposed to

I think [`delete pc._streams[stream.id];`](https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L286) needs also needs to attempt to delete the streamId of the stream deleted by [`delete pc._reverseStreams[(pc._streams[stream.id] ?
 pc._streams[stream.id].id : stream.id)];`](https://github.com/webrtc/adapter/blob/master/src/js/chrome/chrome_shim.js#L284-L285).

**Comment by fippo** [comment]
I think I fixed that in #682 (which is not published on npm yet)

**Comment by ianwremmel** [comment]
Oh, cool. I'll try that out and see if it works better than my fix. (Mine is kind of a disaster by way of additional prototype hacking in my source code). Any idea when #682 will be published to npm?

**Comment by ianwremmel** [comment]
hmm, #682 doesn't seem to solve the problem I'm seeing. My terrible hack is as follows (I'm not sure which method for determining `streamsId` is appropriate, but both seem to work equally):

```js
try {
  const origRemoveStream = window.RTCPeerConnection.prototype.removeStream;
  // eslint-disable-next-line complexity
  window.RTCPeerConnection.prototype.removeStream = function removeStream(stream) {
    // eslint-disable-next-line consistent-this
    const pc = this;

    let streamsId;
    let reverseStreamsId;

    if (pc._streams || pc._reverseStreams) {
      reverseStreamsId = pc._streams[stream.id] ? pc._streams[stream.id].id : stream.id;
      streamsId = pc._reverseStreams[reverseStreamsId] ? pc._reverseStreams[reverseStreamsId].id : stream.id;
      // streamsId = pc._reverseStreams[pc._streams[stream.id] ? pc._streams[stream.id].id : stream.id].id;
    }

    Reflect.apply(origRemoveStream, pc, [stream]);

    if (streamsId) {
      Reflect.deleteProperty(pc._streams, streamsId);
    }

    if (reverseStreamsId) {
      Reflect.deleteProperty(pc._reverseStreams, reverseStreamsId);
    }

  };
}
catch (err) {
  // eslint-disable-next-line no-console
  console[process.env.NODE_ENV === `production` ? `info` : `warn`](`Failed to apply webrtc patch. Are we running in an environment that disallows altering globals?`, err);
}

try {
  // eslint-disable-next-line global-require
  require(`webrtc-adapter`);
}
catch (err) {
// eslint-disable-next-line no-console
  console[process.env.NODE_ENV === `production` ? `info` : `warn`](`Failed to apply adapter.js. Are we running in an environment that disallows altering globals?`, err);
}
```

**Comment by fippo** [comment]
Is this what you're seeing?
```
navigator.mediaDevices.getUserMedia({audio: true, video: true})
.then(stream => {
  var pc = new RTCPeerConnection();
  var sender = pc.addTrack(stream.getVideoTracks()[0], stream);
  pc.removeTrack(sender);
  console.log(pc._streams);
});
```
i.e. it shows pc._streams as not empty. And as you say, this seems to be caused by calling pc.removeStream with the internal mapped stream instead of the external one which... makes things more complicated.

Can you give it a try with ```pc.removeStream(pc._reverseStreams[stream.id]);``` in line 459?

if that is not the issue: can you add console.log traces to all addStream/removeStream and addTrack/removeTrack so it becomes more clear what happens?

**Comment by ianwremmel** [comment]
yep, it looks like that combined with #682 takes care of it
